name: meiguoshushu
favicon: null
layout_spectrum: 0.14308
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73b5ff'
    - '#6b6c71'
    - '#e5dfcf'
    - '#4a4742'
    - '#0f0f11'
  brandStrength: 0.7077288099098951
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5668995655141771
purpose: []
