name: meiguoshushu
favicon: null
layout_spectrum: 0.14308
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: "<script>   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)   })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');    ga('create', 'UA-298781-13', 'auto');   ga('send', 'pageview');  </script>"
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73b5ff'
    - '#6b6c71'
    - '#e5dfcf'
    - '#4a4742'
    - '#0f0f11'
  brandStrength: 0.7077288099098951
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5668995655141771
purpose: []
